/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_iproc_NativeInterface */

#ifndef _Included_xtvapps_iproc_NativeInterface
#define _Included_xtvapps_iproc_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtvapps_iproc_NativeInterface
 * Method:    setMatrix
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_xtvapps_iproc_NativeInterface_setMatrix
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     xtvapps_iproc_NativeInterface
 * Method:    process
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_xtvapps_iproc_NativeInterface_process
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
